# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "00263cc972592ba89c7abcfc546aa76f"
application_url = "https://shopity.onrender.com"
embedded = true
name = "shopity"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [ "https://shopity.onrender.com/api/auth/callback" ]

[webhooks]
api_version = "2026-07"

[build]
automatically_update_urls_on_dev = true
